- name: To download nginx
  hosts: node
  become: yes
  tasks:
  - name: install nginx package
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.bultin.service:
      name: nginx
      state: started
