- name: writing condition play-book
  host: localhost
  tasks:
    - name: checking user is availbale or not
      ansible.builtin.command: id roboshop
      register: user # user is variable to store id 
      ignore_errors: true
    - name: print variable user
      ansible.bultin.debug: 
        msg: "user output is :{{user}}"
    - name: print exit status code
      ansible.builtin.debug:
        msg: "exit status is :{{user.rc}}"
    - name: create user 
      ansible.builtin.user:
        name: roboshop
      when: user.rc != 0