- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: printing loop values
      ansible.builtin.debug:
        msg: "The loop values are : {{item}}"
      loop:
        - ramesh
        - suresh
        - jaga
        - madhu
