- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: printing loop values
      ansible.builtin.debug:  # ansible.builtin.package:
        msg: "The loop values are : {{item}}"  # name: "{{item}}"
      loop:
        - ramesh
        - suresh
        - jaga
        - madhu
